### ISSUE TITLE
todo: baseline

### ISSUE THREAD

**Issue by nstalways** [nstalways/24-LG-Aimers-Phase2#4]
## Background
- 본격적인 실험을 진행하기에 앞서, 주최 측에서 제공한 데이터 및 코드를 바탕으로 baseline으로 사용할 모델을 구현한다.

## To-Do
- [x] 주최 측에서 제공한 데이터 및 코드를 저장소에 이식
- [x] 성능 재현을 위해, `seed setting` 함수 구현
- [x] 기타 필요 함수들 초기 구현

## See Also
-
