### ISSUE TITLE
todo: 학습 데이터에 대한 기초 EDA

### ISSUE THREAD

**Issue by nstalways** [nstalways/24-LG-Aimers-Phase2#7]
## Background
- 본격적인 실험에 앞서, 학습 데이터에 대한 기초 EDA를 수행하여 데이터의 특성을 파악합니다.

## To-Do
- [x] 결측치 확인
- [x] 기초 통계량 확인
- [x] feature별 분포 확인
- [x] feature간 상관 관계 확인

## See Also
-
